### ISSUE TITLE
Create basic house

### ISSUE THREAD

**Issue by aalekseev** [lapin-games/birdy-assets#1]
Let's start with the base house model and then will create small variations from it.
@aalekseev please add reference images in this tread

**Comment by aalekseev** [comment]
1. ![2f2510f9077c0e20834b0f99f925b4b2](https://user-images.githubusercontent.com/7049500/61169602-396ae780-a568-11e9-8b0c-a68dc73fe8e6.jpg)
1. ![03c1edea8aa37c2a74ef35d29f89b8fb](https://user-images.githubusercontent.com/7049500/61169604-396ae780-a568-11e9-98cc-67ab4251e812.jpg)
1. ![3fb5ddd8a14cde5df36b99eebf56adae](https://user-images.githubusercontent.com/7049500/61169605-3a037e00-a568-11e9-9bea-2f9c40c2cad7.jpg)
1. ![006c1cca99e75e36f243ef1a72c5a55f](https://user-images.githubusercontent.com/7049500/61169606-3a037e00-a568-11e9-8c62-14898e1ff560.jpg)
1. ![7b1d80449332e580881923f8d2fe1249](https://user-images.githubusercontent.com/7049500/61169607-3a037e00-a568-11e9-9636-39714e7220a5.jpg)
1. ![50d1edd8e89aa4613d9624168b18100b](https://user-images.githubusercontent.com/7049500/61169608-3a037e00-a568-11e9-99bc-f9ef4fe27daf.jpg)
1. ![6949f2be532ae9db18a348294329545b](https://user-images.githubusercontent.com/7049500/61169609-3a037e00-a568-11e9-9b6e-6c0a864a3200.jpg)
1. ![7730b70df63f0ddfe7d523b1867fed49](https://user-images.githubusercontent.com/7049500/61169610-3a9c1480-a568-11e9-84ad-a68e0ce097d8.jpg)
1. ![8151305767c23836bc83678c89b84832](https://user-images.githubusercontent.com/7049500/61169611-3a9c1480-a568-11e9-9738-af600ab41a3c.jpg)
1. ![a0da08fe4cf619c6a50a8c5066f6855b](https://user-images.githubusercontent.com/7049500/61169612-3a9c1480-a568-11e9-980e-05f9be7a1690.jpg)
1. ![aa078b62de13398b30772a86ec89fd07](https://user-images.githubusercontent.com/7049500/61169613-3a9c1480-a568-11e9-88a4-b4c37e7f29a6.jpg)
1. ![bd5e22ad88343fa4531c2c010707ac2f](https://user-images.githubusercontent.com/7049500/61169615-3b34ab00-a568-11e9-8033-2f31169f837f.jpg)
1. ![bd5e22ad88343fa4531c2c010707ac2f2](https://user-images.githubusercontent.com/7049500/61169616-3b34ab00-a568-11e9-8112-9f1a43c8dff6.jpg)
1. ![Building-25](https://user-images.githubusercontent.com/7049500/61169617-3b34ab00-a568-11e9-8e1e-05882b4ecf6c.png)
1. ![buildings_buildings_0084_01_preview](https://user-images.githubusercontent.com/7049500/61169618-3b34ab00-a568-11e9-9522-39316b5f16dc.jpg)
1. ![c46aaca485011312159a828627793845](https://user-images.githubusercontent.com/7049500/61169619-3b34ab00-a568-11e9-8693-a07fde9a56e2.jpg)
1. ![d25b5eb4d806bc688afbeafef014a6eb](https://user-images.githubusercontent.com/7049500/61169620-3bcd4180-a568-11e9-9610-2415c135f00b.jpg)
1. ![d5722ff9384d86da32e1cc87157843c5](https://user-images.githubusercontent.com/7049500/61169621-3bcd4180-a568-11e9-8fcb-248891194d80.jpg)
1. ![d6725335aaaee90adb9ec1a69ee73ae0](https://user-images.githubusercontent.com/7049500/61169622-3bcd4180-a568-11e9-9417-843e30aed73c.jpg)
1. ![eb9091c381f643faf8abf05eb45a5bb6](https://user-images.githubusercontent.com/7049500/61169623-3bcd4180-a568-11e9-9496-8629675c03c3.jpg)
1. ![Free-C4D-3D-Car-house-low-poly-model-cinema4d](https://user-images.githubusercontent.com/7049500/61169624-3bcd4180-a568-11e9-83b5-d3e2ad181462.jpg)
1. ![lowpoly_house_by_funcreep_dczrmpj-pre](https://user-images.githubusercontent.com/7049500/61169625-3bcd4180-a568-11e9-9e7b-908e8238287d.jpg)
1. ![maxresdefault](https://user-images.githubusercontent.com/7049500/61169626-3c65d800-a568-11e9-8d33-1fc5aea2bc95.jpg)
1. ![notting-hill-london-6](https://user-images.githubusercontent.com/7049500/61169627-3c65d800-a568-11e9-90af-d2b9a9bc95cb.png)
1. ![simple-buildings](https://user-images.githubusercontent.com/7049500/61169628-3c65d800-a568-11e9-8828-75b8138afb1c.jpg)
1. ![test](https://user-images.githubusercontent.com/7049500/61169630-3c65d800-a568-11e9-9f4b-e3e016cea6a4.png)

**Comment by aalekseev** [comment]
@ALapina please look them over and decide which one we will be using :)

**Comment by ALapina** [comment]
Мне кажется, хорошо подойдут простые, цветные дома. Их можно расплодить, поменять цвет и поставить впритык друг к другу. 
Если хочется ещё доп домов, то можно что то повыше, что выделялось бы на фоне этих одинаковых цветных домов. Например как на 3 и 5 вариант.

Мне ещё нравиться подборка домов на 6 картинке. Нужно будет запомнить на будущее =)

P.S. Предложенные варианты надо бы нумеровать, что бы на них удобнее было ссылаться.

**Comment by aalekseev** [comment]
I agree :) I like #13 and #20 the most I think

**Comment by aalekseev** [comment]
![test](https://user-images.githubusercontent.com/7049500/61173545-8321f500-a59d-11e9-9880-101e06635c03.png)
Final result, not happy with it, but it is a start
